### ISSUE TITLE
Navbar Issues

### ISSUE THREAD

**Issue by jannickbath** [EdwardAbboud/Midist-website#20]
## Desktop-Navbar

1. Should be at the top of the page (just for smaller screens)
2. Should be sticky

## Mobile-Navbar
1. Should be hidden, if the desktop version of the page is viewed
2. Icon should be used as **toggle** not just for opening the burger-menu

**Comment by EdwardAbboud** [comment]
Yes! indeed, those features are a work in progress! the navbar will be sticky but will not start on the top of the page, only when scrolled it will be on top
