### ISSUE TITLE
Way too high contrast.

### ISSUE THREAD

**Issue by jannickbath** [EdwardAbboud/Midist-website#7]
## Context

The contrast is way too high and therefore very unappealing.

## Process

1. User navigates to the website.
2. He will notice that its way too bright.

## Expected result

User finds the website interesting and quite appealing, so he browses through it to find some more information.

## Current result

User finds the website and probably regrets it, because he got an headache.

## Possible Fix

Remove the `filter: invert(1)` from the `<main>` element, because its quite nonsense.

**Comment by EdwardAbboud** [comment]
Thanks for the tips! This is however the website for users with the dark theme enabled. If you enter that mode on your device all those problems are fixed
